### ISSUE TITLE
Use pjax:end

### ISSUE THREAD

**Issue by fregante** [github-linker/injection#11]
`pjax:end` seems to work just as well as the current code, if not faster and more efficiently:

![pjax:end demo](https://user-images.githubusercontent.com/1402241/27983908-13767b4e-63fb-11e7-87ec-3a69cf08d4ee.gif)

Perhaps `injection/index.js` should just be this:

```
function gitHubInjection(cb) {
  document.addEventListener('pjax:end', cb);
  cb();
}
```

**Comment by stefanbuck** [comment]
This looks interesting. Will review it in detail later today

**Comment by stefanbuck** [comment]
This is awesome, great stuff 👍  How did you figured this out? Did you inspect GitHub's source code? Anyway, I'll update the package

**Comment by fregante** [comment]
Wait! Let's get #10 in first! 😃
If you want this I'll change the PR. 

I just saw it here: https://github.com/sindresorhus/refined-github/blob/master/src/content.js#L519

**Comment by stefanbuck** [comment]
I think many changes you made in #10 aren't needed anymore if we go with `pjax:end`. Therefore my idea was to close #10 and implement `pjax:end` straight away (see #12)

**Comment by fregante** [comment]
👍

**Comment by stefanbuck** [comment]
Merge and released
